### ISSUE TITLE
Send payment to user from home by selecting contact

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#1]
User should be able to send a payment by
1. click on FAB on home
2. select contact from contacts
3. enter amount and subject
4. confirm/sign payment

### Tasklist
- [x] create FAB on home view
- [x] #2 create contact selection view
- [x] #3 create send view with inputs for amount and subject
- [x] #4 create confirm/sign view
