### ISSUE TITLE
Add contact by scanning QR code

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#12]
User should be able to add a contact by scanning the QR code of another user from the home view.
Home view -> Click on FAB -> Click on **Add contact** -> QR scanner

#### Tasks
- [ ] ~~FAB option **Add contact** on home view~~
- [x] FAB option **Scan QR** on home view to add contact
- [x] implement QR scanner

#### Related
- #13
