### ISSUE TITLE
Generate and display my account QR code

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#13]
User should be able to show his account QR code, so other users can add him by scanning his QR code. The QR code should contain:
- address
- username

#### Tasks
- [x] generate QR code
- [x] display QR code
- [x] possibility to share
