### ISSUE TITLE
On-boarding view for user who is on-boarding

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#15]
User should be able to optionally set the amount of creditline + amount of payment/receivement when on-boarding a new user.

#### Tasks
- [ ] information text on how on-boarding works
- [ ] input for creditline
- [ ] input for payment + radio button (send or receive)
