### ISSUE TITLE
Contact selection after clicking send

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#2]
User should be able to select a contact from a contact list view after clicking `send` on FAB in home

### Tasks
- [x] search bar
- [x] back button
- [x] scan QR code list item
- [ ] alphabet scroll bar
- [x] contacts with balances

![1-send - select contact](https://user-images.githubusercontent.com/17645687/27434159-05743afe-5758-11e7-828d-ab487114ffd8.png)
