### ISSUE TITLE
Enter amount and subject for sending payment

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#3]
User should be able to enter the amount and subject of the payment he wants to send to the seleted user.

### Tasks
- [x] back button
- [x] input for amount
- [x] input for subject (optional)
- [x] check button
- [ ] name of receiver

![1-send - contact with tl - enter](https://user-images.githubusercontent.com/17645687/27434733-f4633178-5759-11e7-9e61-88a16de3ba5a.png)
