### ISSUE TITLE
Enter optionally amount and subject for receiving payment

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#7]
User should optionally have the possibility to specify the amount and subject of payment he wants to receive so that the sender doesn't have to enter the information manually.

### Tasks
- [x] input for amount
- [x] input for subject
- [ ] information text about inputs being optional
- [x] check button to create QR code

![1-receive - enter](https://user-images.githubusercontent.com/17645687/27436386-5f07d33a-575f-11e7-873b-c56af6dbb3a7.png)
