### ISSUE TITLE
Generate and display QR code for receiving payment

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#8]
The generated QR code should contain
- address of receiver
- amount (optional)
- subject (optional)

In addition there should be the possibility to share and copy the QR as a link.

### Tasks
- [x] generate QR code
- [x] display QR code
- [x] button to share QR code via a messenger
- [ ] button to copy QR code
- [x] back button

![1-receive - qr code](https://user-images.githubusercontent.com/17645687/27436828-b5fd3378-5760-11e7-87d5-a90785f307a8.png)
